# Generated by Django 5.2 on 2025-05-05 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_posts_author_posts_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterField(
            model_name='posts',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='get_posts', to='blog.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 14, 35, 58, 53387, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
