# Generated by Django 5.2 on 2025-05-09 15:48

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options_alter_posts_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 9, 15, 48, 14, 882538, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
