# Generated by Django 5.2 on 2025-05-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_options_project_git_hub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='orden'),
        ),
    ]
