# Generated by Django 5.2 on 2025-05-09 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_posts_content_alter_posts_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 9, 17, 7, 25, 825050, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
