# Generated by Django 5.2.3 on 2025-06-22 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_posts_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 22, 15, 57, 11, 587330, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
