# Generated by Django 5.2.3 on 2025-06-22 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 22, 15, 57, 11, 598559, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
