# Generated by Django 5.2 on 2025-05-02 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['-created'], 'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.RemoveField(
            model_name='books',
            name='description',
        ),
        migrations.AddField(
            model_name='books',
            name='sinopsis',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Sinopsis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='link_compra',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace de compra'),
        ),
    ]
